# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL.xci
# IP: The module: 'PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL.xci
# IP: The module: 'PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
