# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param simulator.modelsimInstallPath E:/software/modelsim2019/win64
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.cache/wt [current_project]
set_property parent.project_path E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_i2c/i2c_master_defines.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_defines.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/config.v
}
set_property file_type "Verilog Header" [get_files E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_i2c/i2c_master_defines.v]
set_property file_type "Verilog Header" [get_files E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_defines.v]
set_property file_type "Verilog Header" [get_files E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/config.v]
read_verilog -library xil_defaultlib {
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/AESkeyprocess.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/DESkey.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/DESkeys.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/ENCNEW.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/E_box.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/InvMixColumns.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/InvSubBytes.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/MixColumns.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/P.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S1.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S2.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S3.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S4.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S5.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S6.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S7.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/S8.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/S_box.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/SubBytes.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/adv_timer_apb_if.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/imports/new/aesden.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/aesinitkeyprocess.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/Desktop/apb_Des_Aes.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/apb_adv_timer.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_gpio/apb_gpio.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_i2c/apb_i2c.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_spi_master/apb_spi_master.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_uart/apb_uart.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/clkdivider.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/comparator.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/desL.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/desdekey.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/desf.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_biu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_clk_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_clkgate.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_core.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_cpu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_cpu_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_dtcm_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_dtcm_ram.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_alu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_alu_bjp.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_alu_csrctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_alu_dpath.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_alu_lsuagu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_alu_muldiv.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_alu_rglr.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_branchslv.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_commit.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_csr.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_decode.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_disp.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_excp.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_longpwbck.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_nice.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_oitf.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_regfile.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_exu_wbck.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_ifu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_ifu_ifetch.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_ifu_ift2icb.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_ifu_litebpu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_ifu_minidec.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_irq_sync.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_itcm_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_itcm_ram.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_lsu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_lsu_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_reset_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/soc/e203_soc_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/core/e203_srams.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_clint.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_gfcm.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_hclkgen.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_hclkgen_rstsync.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_main.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_mems.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_nice_core.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_perips.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_plic.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_pll.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_pllclkdiv.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/subsys/e203_subsys_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_i2c/i2c_master_bit_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_i2c/i2c_master_byte_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/init_process.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/input_stage.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_uart/io_generic_fifo.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/keyprocess.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/left_shiftera.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/left_shifterb.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/prescaler.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/sources_1/new/process.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/general/sirv_1cyc_sram_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_AsyncResetReg.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_AsyncResetRegVec.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_AsyncResetRegVec_1.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_AsyncResetRegVec_129.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_AsyncResetRegVec_36.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_DeglitchShiftRegister.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_LevelGateway.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_ResetCatchAndSync.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_ResetCatchAndSync_2.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_aon.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_aon_lclkgen_regs.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_aon_porrst.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_aon_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_aon_wrapper.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_clint.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_clint_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/debug/sirv_debug_csr.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/debug/sirv_debug_module.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/debug/sirv_debug_ram.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/debug/sirv_debug_rom.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_expl_axi_slv.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_flash_qspi.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_flash_qspi_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/general/sirv_gnrl_bufs.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/general/sirv_gnrl_dffs.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/general/sirv_gnrl_icbs.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/general/sirv_gnrl_ram.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_hclkgen_regs.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/fab/sirv_icb1to16_bus.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/fab/sirv_icb1to2_bus.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/fab/sirv_icb1to8_bus.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/debug/sirv_jtag_dtm.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_jtaggpioport.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/mems/sirv_mrom.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/mems/sirv_mrom_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_plic_man.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_plic_top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_pmu.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_pmu_core.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_qspi_arbiter.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_qspi_fifo.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_qspi_media.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_qspi_physical.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_queue.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_queue_1.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_repeater_6.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_rtc.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/general/sirv_sim_ram.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_spi_flashmap.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/general/sirv_sram_icb_ctrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_tl_repeater_5.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_tlfragmenter_qspi_1.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_tlwidthwidget_qspi.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/sirv_wdog.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_spi_master/spi_master_apb_if.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_spi_master/spi_master_clkgen.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_spi_master/spi_master_controller.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_spi_master/spi_master_fifo.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_spi_master/spi_master_rx.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_spi_master/spi_master_tx.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/timer_cntrl.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/timer_module.v
  E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/imports/new/top.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_uart/uart_interrupt.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_uart/uart_rx.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_uart/uart_tx.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/perips/apb_adv_timer/up_down_counter.v
  E:/BaiduNetdiskDownload/E203_P2/E203_RTL/aic_rv32.v
}
read_ip -quiet E:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL.xci
set_property used_in_implementation false [get_files -all e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL_board.xdc]
set_property used_in_implementation false [get_files -all e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL.xdc]
set_property used_in_implementation false [get_files -all e:/BaiduNetdiskDownload/E203_P2/E203_Zynq_7010/E203_Zynq_7010.srcs/sources_1/ip/PLL/PLL_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/BaiduNetdiskDownload/E203_P2/XDC/E203_ZYNQ_7010.xdc
set_property used_in_implementation false [get_files E:/BaiduNetdiskDownload/E203_P2/XDC/E203_ZYNQ_7010.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top aic_rv32 -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef aic_rv32.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file aic_rv32_utilization_synth.rpt -pb aic_rv32_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
